// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdojWuDrmzXAeeHacT6XTucAWKmggfhC0',
    appId: '1:187848207220:web:b571592a7207fe13109a21',
    messagingSenderId: '187848207220',
    projectId: 'love-of-care',
    authDomain: 'love-of-care.firebaseapp.com',
    storageBucket: 'love-of-care.appspot.com',
    measurementId: 'G-4HSJPDQEC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjyggg4foMpgd1_dnGvCY2VF01HkCCu_Y',
    appId: '1:187848207220:android:747f55749bb1c694109a21',
    messagingSenderId: '187848207220',
    projectId: 'love-of-care',
    storageBucket: 'love-of-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNe-rQWDG1RSbJuB_497DJGvjla7Ccj_Y',
    appId: '1:187848207220:ios:81757e4793900dbc109a21',
    messagingSenderId: '187848207220',
    projectId: 'love-of-care',
    storageBucket: 'love-of-care.appspot.com',
    iosClientId: '187848207220-i89qg73tom7bu0ha6ktiltk01lsv9qvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );
}
